apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-env-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: dev
            valueFile: dev/dev-values.yaml
          - name: staging
            namespace: staging
            valueFile: stage/staging-values.yaml
            
  template:
    metadata:
      name: 'cloud7-api-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Chetan77-hub/cloud7-dataapi-spring-charts.git
        targetRevision: HEAD
        path: .
        helm:
          valueFiles:
            - '{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
